services:
  - type: web
    name: one-for-all
    env: node
    plan: free
    buildCommand: npm run render-postbuild
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        fromService:
          type: web
          name: one-for-all
          property: url
    healthCheckPath: /test
